### ISSUE TITLE
Reading Image

### ISSUE THREAD

**Issue by vaibagga** [CropAi/Data-Modeling#1]
Create a python module for reading images from the directory, their labels and saving the data in an h5 file. 
Within the module, create a function for loading the whole dataset

**Comment by Mansi145** [comment]
Are we working locally with the Kaggle files or can we use the Kaggle API to directly access the dataset?

**Comment by voldemortuk** [comment]
I would like to work on the issue

**Comment by neversettle17-101** [comment]
I would like to work on this issue

**Comment by abhishekgupta368** [comment]
I would like to work on it can you please assign me this task

**Comment by NeerajSirvisetti** [comment]
Can I work on this?

**Comment by NeerajSirvisetti** [comment]
Can I work on this?

**Comment by gshanbhag525** [comment]
> Are we working locally with the Kaggle files or can we use the Kaggle API to directly access the dataset?

You can download the dataset on your local machine.

**Comment by gshanbhag525** [comment]
@Valdermaut You have one day to work on this issue.

**Comment by TheTrailblazer09** [comment]
Hi! Can I  work on this issue?

**Comment by gshanbhag525** [comment]
@Valdermaut Hi, you have 6 hours to work on this issue and submit the PR.
Otherwise I will assign the issue to next participant in this thread.

**Comment by neversettle17-101** [comment]
@gshanbhag525  My exams are going on right now. I would like to work on this issue right after they get over( 7th march ). Please assign this issue to the participant after me. I will work on it later.

**Comment by voldemortuk** [comment]
@gshanbhag525  im done with it.

**Comment by Akansha2202** [comment]
assign me this issue

**Comment by Garimagupta85** [comment]
I would like to work on this issue.

**Comment by preeti13456** [comment]
Interested

**Comment by GowthamChowta** [comment]
Interested

**Comment by Mansi145** [comment]
I would like to work on this issue. Can you assign it to me? I can make it work in one day.

**Comment by jgini** [comment]
hi i would like to work on this.

**Comment by Shatakshi21** [comment]
I would like to work on this. Infact,I have done this

**Comment by abhishekgupta368** [comment]
can I do it?
