### ISSUE TITLE
Add Tensorflow setup for Linux users

### ISSUE THREAD

**Issue by gunjanmimo** [CropAi/Data-Modeling#13]
Tensorflow setup for windows is added.
Linux users need TensorFlow setup and an installation guide to work with TensorFlow.

**Comment by TheTrailblazer09** [comment]
I would like to work on this issue

**Comment by gunjanmimo** [comment]
@TheTrailblazer09, I have already started working on this issue.

**Comment by jyoti22rjc** [comment]
I would like to work on this issue

**Comment by ghost** [comment]
I would like to work on this issue

**Comment by gshanbhag525** [comment]
Add a sub heading in Readme.md file as "Tensorflow Installtion on Linux" preferably for Ubuntu. And send a PR by tomorrow. @gunjanmimo

**Comment by jyotikrjc** [comment]
> Add a sub heading in Readme.md file as "Tensorflow Installtion on Linux" preferably for Ubuntu. And send a PR by tomorrow. @gunjanmimo

ok
