### ISSUE TITLE
Remove folder for Installing tensorflow on windows guide

### ISSUE THREAD

**Issue by gshanbhag525** [CropAi/Data-Modeling#17]
Remove the separate folder created for tf installtion guide on windows. Create a heading in readme.md file called "Installtion Guide" and Add Subheadings as Tensorflow Installtion on Windows.

**Comment by annu12340** [comment]
I would like to work on this issue. Please assign it to me

**Comment by Mansi145** [comment]
Can I work on this? It should not take me more than half an hour to get this done.

**Comment by gshanbhag525** [comment]
@Mansi145 ok u do it
