### ISSUE TITLE
Build a model using tf.keras

### ISSUE THREAD

**Issue by gshanbhag525** [CropAi/Data-Modeling#19]
Build a model using tf.keras and also display the confusion matrix for the given model.

**Comment by Mansi145** [comment]
Can I work on this? I'm comfortable working with Keras.

**Comment by shubhamgoel90** [comment]
@gshanbhag525 please can I work on this issue? I have already started working on it. Please Can you assign the issue to me?

**Comment by shubhamgoel90** [comment]
@gshanbhag525 Can you assign this issue to me? I have already started working on this.

**Comment by neversettle17-101** [comment]
Can I work on this? I have implemented a similar model for plant disease detection before.

**Comment by voldemortuk** [comment]
I would like to work on this issue

**Comment by AdityaSingh17** [comment]
I would like to take up this issue.

**Comment by gshanbhag525** [comment]
> Can I work on this? I'm comfortable working with Keras.

How much time you will need to work on this issue?

**Comment by Mansi145** [comment]
Thanks, @gshanbhag525 for assigning me the issue. In what time do you want this to be done? I wanted to give it 3-4 days. Are we fine with that deadline?

**Comment by abhishekgupta368** [comment]
I can make it fast and efficent, can you please assign me?

**Comment by gshanbhag525** [comment]
@Mansi145 You can take 4 days to implement it.
@abhishekgupta368 You can comment on the PR with enhancements once Mansi works on this issue in 4 days.

**Comment by abhishekgupta368** [comment]
ok

**Comment by abhishekgupta368** [comment]
Sir, you told me that in four days, no pull request is created, you will assign me this task.
can you please assign me.
thank you

**Comment by gshanbhag525** [comment]
@abhishekgupta368 Mansi has worked on this issue....You can also take a look at the model she built. And if you have any better ideas you cacn comment here and I will assign this issue to refine this model.

**Comment by abhishekgupta368** [comment]
Can I message you on slack

**Comment by abhishekgupta368** [comment]
I didn't find any issue.

**Comment by gshanbhag525** [comment]
@abhishekgupta368 Its created .

**Comment by shubhamgoel90** [comment]
@gshanbhag525 Please review the Keras model file again. @Mansi145  has trained it on the wrong dataset. She has trained it on 39 classes while it has to be trained on 15 classes ie the given dataset for the project. So, kindly review it again.

**Comment by Mansi145** [comment]
> @gshanbhag525 Please review the Keras model file again. @Mansi145 has trained it on the wrong dataset. She has trained it on 39 classes while it has to be trained on 15 classes ie the given dataset for the project. So, kindly review it again.

Ohh thanks for notifieng this to us @shubhamgoel90. @gshanbhag525 let us know what do you want us to do. I think both Shubham or I are capable to fix this mistake.

**Comment by gshanbhag525** [comment]
Thanks for pointing that out @shubhamgoel90. Since he found the particular issue in the dataset. I would like him to correct this @Mansi145 . I am assigning this issue to u @shubhamgoel90 and your PR I want you to refine it.
