### ISSUE TITLE
Cross Validation

### ISSUE THREAD

**Issue by vaibagga** [CropAi/Data-Modeling#2]
Create a standardized python module for loading and splitting the dataset loaded from h5 file into train and validation splits (do not forget to set seed).

**Comment by aditisingh2362** [comment]
I would like to take up this issue.

**Comment by voldemortuk** [comment]
I would like to work on the issue

**Comment by abhishekgupta368** [comment]
I would like to work on it, can you please assign me this task?

**Comment by aditisingh2362** [comment]
@vaibagga I could not find the h5 file in the dataset link provided. What does it signify?

**Comment by gshanbhag525** [comment]
hi, @aditisingh2362 h5 is keras trained ml model file which you have to create and save once the training is done.

**Comment by aditisingh2362** [comment]
@gshanbhag525 Thanks

**Comment by gshanbhag525** [comment]
@aditisingh2362 Are you still working on this Issue? If not, do let me know so I can reassign it to next person. If yes, I will give you more 24 hrs to work on this issue.

**Comment by aditisingh2362** [comment]
Yes, I'm still working on it.

**Comment by Akansha2202** [comment]
please assign me this issue

**Comment by snehilk1312** [comment]
@gshanbhag525 Are these repos only those who have been selected for gssoc?

**Comment by TheTrailblazer09** [comment]
I would like to work on this issue

**Comment by poojasrinivass** [comment]
I would like to work on this issue

**Comment by voldemortuk** [comment]
I would like to work on this

**Comment by preeti13456** [comment]
Interested

**Comment by GowthamChowta** [comment]
Interested

**Comment by gshanbhag525** [comment]
@Valdermaut You have 24 hours to work on this issue....If not completed will be assigned to next person.

**Comment by Mansi145** [comment]
Hey @gshanbhag525, what's the status of this issue? Can I work on this if no one is working on it?

**Comment by poojasrinivass** [comment]
I have also commented previously on this issue expressing my interest. Could you assign this to me please.

**Comment by voldemortuk** [comment]
@Mansi145  I am done with the issue do check the pull request.

**Comment by suchi12j** [comment]
I want to work on this
