### ISSUE TITLE
Write a python script to load 200 images from each folder of dataset

### ISSUE THREAD

**Issue by gshanbhag525** [CropAi/Data-Modeling#21]
Write a python script to load 200 images from each folder of plants dataset.

**Comment by Mansi145** [comment]
Can you assign this to me?

**Comment by annu12340** [comment]
I also would like to work on this issue

**Comment by AdityaSingh17** [comment]
I would like to take up this issue.

**Comment by gshanbhag525** [comment]
@annu12340 You hv 24 hrs to work on this issue

**Comment by annu12340** [comment]
I have created the pr
