### ISSUE TITLE
Write a method to Convert each imported image into an Array

### ISSUE THREAD

**Issue by gshanbhag525** [CropAi/Data-Modeling#22]
Create a method to Convert each imported image into an Array so that it can be used in further modelling.

**Comment by gshanbhag525** [comment]
Use Cv2 and numpy

**Comment by Mansi145** [comment]
Can I work on this?

**Comment by TheTrailblazer09** [comment]
I want to work on this

**Comment by abhishekgupta368** [comment]
I have do it easy and efficently. can you assign me please.

**Comment by abhishekgupta368** [comment]
what is size of the array and it should be 2d or 1d

**Comment by abhishekgupta368** [comment]
thank you for assigning me
