### ISSUE TITLE
Use pickle library to label binarizer instance 

### ISSUE THREAD

**Issue by gshanbhag525** [CropAi/Data-Modeling#24]
Use pickle library to label binarizer instance and print the issues

**Comment by HarshCasper** [comment]
I would like to work upon this issue. Can you please assign me this issue @gshanbhag525

**Comment by gshanbhag525** [comment]
You have 24 hours @HarshCasper

**Comment by HarshCasper** [comment]
I have completed the part. Kindly review it @gshanbhag525
