### ISSUE TITLE
Requirements text file  

### ISSUE THREAD

**Issue by gshanbhag525** [CropAi/Data-Modeling#3]
Create a requirements text file for this project which will contain all the required libraries and frameworks for doing the data modelling.

**Comment by vvijayalakshmi21** [comment]
Hi, Im interested to take this up

**Comment by gunjanmimo** [comment]
I AM TAKING THIS ISSUE.

**Comment by gunjanmimo** [comment]
@gshanbhag525 sir I have added the list of required libraries and frameworks. please review the pr

**Comment by gshanbhag525** [comment]
> I AM TAKING THIS ISSUE.

Issue is already assigned to @vvijayalakshmi21 .

**Comment by Akansha2202** [comment]
assign me this issue

**Comment by gunjanmimo** [comment]
@gshanbhag525 sir may you add badge in this pr?

**Comment by Mansi145** [comment]
Can I work on this issue? I can make it work in an hour.
