### ISSUE TITLE
Refine Readme file

### ISSUE THREAD

**Issue by gshanbhag525** [CropAi/Data-Modeling#35]
Remove duplicate parts. Follow the same visual appearance of Linux Installationfor Windows Installation

**Comment by annu12340** [comment]
I would like to work on it

**Comment by gshanbhag525** [comment]
Sure go ahead.

**Comment by poojasrinivass** [comment]
I would like to work on this issue. Can you add me to the queue?

**Comment by annu12340** [comment]
Could you please elaborate on what all things should I modifiy in the read me file

**Comment by suchi12j** [comment]
I want to work on this isssue

**Comment by gshanbhag525** [comment]
@poojasrinivass @suchi12j You can put the commands for Installation on Windows Part into code section which will fill horizonatally. You can take a look at the Installation on Linux Part for the understanding.

**Comment by suchi12j** [comment]
I have created one pull request let me know if it requires any changes. I will update it.
