### ISSUE TITLE
Create a python module to detect the spots on plant leaves (Use Kmeans algo)

### ISSUE THREAD

**Issue by gshanbhag525** [CropAi/Data-Modeling#37]
Create a python module to detect the spots on plant leaves. Use image segmentation techniques.
Use Kmeans algorithm

**Comment by prakhar154** [comment]
hi, i would like to work on it

**Comment by abhishekgupta368** [comment]
I ask you for this issue, can you assign me?

**Comment by gshanbhag525** [comment]
> I ask you for this issue, can you assign me?

Yes I want you to create a module for the same but without using kmeans algo but some other algo.. Would you be able to do that . If yes , then I will assign you.

**Comment by abhishekgupta368** [comment]
I will use computer vision with image segmentation that will be fast and efficient.

**Comment by prakhar154** [comment]
@gshanbhag525 I can do this with deep learning. But it will take some time.

**Comment by abhishekgupta368** [comment]
Can you please assign me, please

**Comment by prakhar154** [comment]
@gshanbhag525 I have made a PR for this issue. please review it.

**Comment by abhishekgupta368** [comment]
Can i do this please?
