### ISSUE TITLE
Build a Keras CNN model using Alexnet Architecture

### ISSUE THREAD

**Issue by gshanbhag525** [CropAi/Data-Modeling#38]
Create a keras Convolutional Neural Network on Alexnet arch. Create model checkpoints in the code.

**Comment by xAdvitya** [comment]
I would like to work on this issue

**Comment by AdityaSingh17** [comment]
@gshanbhag525  although I have never created an Alexnet model, I would really like to learn and create one! Could you please share some reference material?

**Comment by AdityaSingh17** [comment]
@gshanbhag525  although I have never created an Alexnet model, I would really like to learn and create one! Could you please share some reference material and assign me this issue?

**Comment by TheTrailblazer09** [comment]
I would like to work on this issue

**Comment by jan-027** [comment]
@gshanbhag525 I have previously worked with GoogleNet and ResNet for transfer learning. I would like to work with this one as well.

**Comment by Mansi145** [comment]
Hey @gshanbhag525. @AdityaSingh17 is working on this issue. If by any unfortunate chance he isn't able to complete the assigned task, I'd like to take up the issue. 😄 ✌️
