### ISSUE TITLE
Create a documentation for how to setup the dataset to work with google collab

### ISSUE THREAD

**Issue by gshanbhag525** [CropAi/Data-Modeling#40]
Create a documentation for how to setup the dataset to work with google collab. 
Give detailed steps. 
The model built in tf.keras is present in jupyter file in this repo. It is present google collab. 
You can refer it too.

**Comment by TheTrailblazer09** [comment]
I would like to work on this issue. however could you explain what does "setup the dataset" exactly means . Does it mean adding your dataset to google drive and accessing it

**Comment by suchi12j** [comment]
I want to work on this

**Comment by gshanbhag525** [comment]
> I would like to work on this issue. however could you explain what does "setup the dataset" exactly means . Does it mean adding your dataset to google drive and accessing it

yes indeed.

**Comment by gshanbhag525** [comment]
24 hours would be more then enaugh for this. Create a nice Documentation @TheTrailblazer09 @suchi12j .

**Comment by TheTrailblazer09** [comment]
@gshanbhag525 could you explain a little what we have to do

**Comment by gshanbhag525** [comment]
Dataset is present in kaggle. Produce detailed steps on how to import that datset in google collab.
