### ISSUE TITLE
Predict the new test images

### ISSUE THREAD

**Issue by gshanbhag525** [CropAi/Data-Modeling#41]
Use the keras model created to predict the new test images and the disease class it follows.
Display the image too using matplotlib library.

**Comment by xAdvitya** [comment]
I would like to work on this issue

**Comment by TheTrailblazer09** [comment]
I would also like to work on it

**Comment by gshanbhag525** [comment]
@Advitya-sharma Any update on this issue

**Comment by AdityaSingh17** [comment]
If there is no update, I would like to take this issue.

**Comment by nancysingh24** [comment]
> Use the keras model created to predict the new test images and the disease class it follows.
> Display the image too using matplotlib library.

I would to like to work on this issue.

**Comment by TheTrailblazer09** [comment]
Hi 
I am sorry for the delay. I will push it within the next 48 hours.
Could you please tell me which test images should I use as all Kaggle images have been used in training?

**Comment by gshanbhag525** [comment]
@TheTrailblazer09 Right now use the one from the dataset only.

**Comment by gshanbhag525** [comment]
@TheTrailblazer09 import one image

**Comment by gshanbhag525** [comment]
@TheTrailblazer09  Also push the PR to devt branch

**Comment by gshanbhag525** [comment]
Its been more then 48 hours @TheTrailblazer09

**Comment by TheTrailblazer09** [comment]
Hi
Sorry but the model that was trained is not giving the correct output. It is giving the 6th label for every picture. I am working on it I will surely submit it by tonight
