### ISSUE TITLE
detect spots on plant leaves using Opencv

### ISSUE THREAD

**Issue by gshanbhag525** [CropAi/Data-Modeling#47]
detect spots on plant leaves using Opencv and image segmentation techniques

**Comment by abhishekgupta368** [comment]
I would like to work with it, please assign me this issue

**Comment by abhishekgupta368** [comment]
why beginner?

**Comment by abhishekgupta368** [comment]
Thanks

**Comment by nancysingh24** [comment]
> detect spots on plant leaves using Opencv and image segmentation techniques

I would like to work on this issue.
