### ISSUE TITLE
Documentation for doing EDA Analysis

### ISSUE THREAD

**Issue by gshanbhag525** [CropAi/Data-Modeling#5]
Create documentation for doing EDA Analysis on the dataset.

**Comment by vvijayalakshmi21** [comment]
Hi, I would like to take this up.

**Comment by Aju100** [comment]
hello i would like to take it too

**Comment by HarshMehta2468** [comment]
Hey,If PR not made in stipulated time, i'd surely like to take up this issue.

**Comment by GowthamChowta** [comment]
Hi, I am interested in doing this.

**Comment by poojasrinivass** [comment]
I would like to work on this issue

**Comment by preeti13456** [comment]
Interested

**Comment by gshanbhag525** [comment]
@gunjanmimo Your commit includes code related to csv file. The issue asks EDA on Image dataset.

**Comment by gshanbhag525** [comment]
@Aju100 Would you be able to work on this issue?

**Comment by Aju100** [comment]
sure

**Comment by suchi12j** [comment]
I want to work on this isssue

**Comment by gshanbhag525** [comment]
@Aju100 ANy update on this issue PR?

**Comment by abhishekgupta368** [comment]
Assign me please, so that, I can work on it

**Comment by abhishekgupta368** [comment]
Can you Assign me, So that, I can make EDA of it?
