### ISSUE TITLE
Image segmentation using Mask R-CNN model

### ISSUE THREAD

**Issue by gshanbhag525** [CropAi/Data-Modeling#52]
Use Image segmentation techniques to detect spots on leaves. Use deep learning.

**Comment by prakhar154** [comment]
i would like to work on it

**Comment by AdityaSingh17** [comment]
I would like to take this up.

**Comment by gshanbhag525** [comment]
@prakhar154 Which DL model are u planning to use

**Comment by prakhar154** [comment]
> @prakhar154 Which DL model are u planning to use

i will train Mask R-CNN

**Comment by nancysingh24** [comment]
> Use Image segmentation techniques to detect spots on leaves. Use deep learning.

I would like to work on this issue.

**Comment by Himabindugssn** [comment]
I would like to take up this issue.

**Comment by gshanbhag525** [comment]
@Himabindugssn @nancysingh24  Which DL model you are planning to use if I assign you this issue?

**Comment by abhishekgupta368** [comment]
can you please assign me this issue.

**Comment by Himabindugssn** [comment]
@gshanbhag525 I would use ResNet. It would give less error rate as compared to other models.

**Comment by nancysingh24** [comment]
> @Himabindugssn @nancysingh24 Which DL model you are planning to use if I assign you this issue?

AlexNet and GoogLeNet are best for large scale visual recognition.

**Comment by gshanbhag525** [comment]
@nancysingh24 @Himabindugssn Alexnet arch and Resnet is already implemented by other participants

**Comment by Himabindugssn** [comment]
@gshanbhag525 can I try UNet?

**Comment by gshanbhag525** [comment]
Sure go ahead @Himabindugssn I will create an issue.

**Comment by abhishekgupta368** [comment]
can you assign me?

**Comment by gshanbhag525** [comment]
Any updates on this issue? @prakhar154

**Comment by prakhar154** [comment]
@gshanbhag525 i am working on it, sorry for the delay i was busy with internship

**Comment by Mansi145** [comment]
Hey, @gshanbhag525 what's the update on the issue? Can I work on this?

**Comment by gshanbhag525** [comment]
Yes ..u can work on this. @Mansi145

**Comment by Kuljeet-123** [comment]
@gshanbhag525 Can I work on this issue??

**Comment by abhishekgupta368** [comment]
Please Allot me, I will do it.
