### ISSUE TITLE
Tidy up repository!!

### ISSUE THREAD

**Issue by gshanbhag525** [CropAi/Data-Modeling#53]
Create 2 folders 

1. modules
Put these python module files in the modules folder. eg. "Image_To_array.py" , "label_binarizer_instance.py"

2. docs
Put these markdown files in the docs folder. eg. "transfer learning.md"
Extract "Installtion steps for tensorflow" from README.md and paste them in the docs folder as two separate md files for each OS

> Give links to these files in the Readme file.

**Comment by Aman-Codes** [comment]
@gshanbhag525 I am a GSSOC participant and I would like to work on this issue. Please assign it to me.

**Comment by Aman-Codes** [comment]
@gshanbhag525  Do I also need to add load_images.py file to modules folder?

**Comment by gshanbhag525** [comment]
@Aman-Codes No dont add it.

**Comment by gshanbhag525** [comment]
@Aman-Codes Also there are some more modules that are to be reviewed by mentors.

**Comment by gshanbhag525** [comment]
Create on more folder called "notebooks" and add all the jupyter notebooks from master branch to "notebooks" directory.

**Comment by gshanbhag525** [comment]
Do keep Cropai-keras jupyter notebook in the master branch....rest all can be moved to notebooks direcctory

**Comment by gshanbhag525** [comment]
Except "lable_images" file...move all other py module files to "modules" direcctory

**Comment by abhishekgupta368** [comment]
can you assign me?
