### ISSUE TITLE
Documentation for How to setup tensorflow on Windows

### ISSUE THREAD

**Issue by gshanbhag525** [CropAi/Data-Modeling#6]
You have to write detailed steps as how to setup tesnorflow on windows machine for data modelling.

**Comment by HarshCasper** [comment]
Hello, @gshanbhag525 I would like to work on this issue as a participant for GSSOC'2020. I have ample experience in writing documentation and feel that I am best fit to execute this task. Kindly assign me this issue.

**Comment by HarshCasper** [comment]
I have added a [Pull Request #9](https://github.com/CropAi/Data-Modeling/pull/9) to resolve this issue. Kindly review.
