### ISSUE TITLE
Load .h5 file from google drive

### ISSUE THREAD

**Issue by gshanbhag525** [CropAi/Data-Modeling#71]
Create a py file and Load .h5 file from google drive.

**Comment by AdityaSingh17** [comment]
I would like to work on this issue.

**Comment by abhishekgupta368** [comment]
I will do it, assign me please

**Comment by gshanbhag525** [comment]
@AdityaSingh17 @abhishekgupta368 ok Both of you work on this. Its fairly an easy issue. WOrk on it and sent the PR as fast as possible.

**Comment by AdityaSingh17** [comment]
Which .h5 are we loading exactly? I don't see any in the repository.

**Comment by AdityaSingh17** [comment]
Where is the .h5 located?

**Comment by gshanbhag525** [comment]
@AdityaSingh17 Are you der on slack?

**Comment by AdityaSingh17** [comment]
@gshanbhag525 Yes!

**Comment by gshanbhag525** [comment]
@AdityaSingh17 Jus Dm me
