### ISSUE TITLE
List all the crop leaf disease categories in text file 

### ISSUE THREAD

**Issue by tanishq9** [CropAi/Data-Modeling#74]
We require this file in our backend repository, so you should make a pull request for this issue :
https://github.com/CropAi/Backend/issues/11

**Comment by abhishekgupta368** [comment]
i want to do

**Comment by abhishekgupta368** [comment]
I have done data analysis of the dataset and can do it better.

**Comment by gshanbhag525** [comment]
@abhishekgupta368 @tanishq9 This issue is duplicate and have already been solved in the Backend repo. I am closing this issue.
