### ISSUE TITLE
Image segmeantation using UNet Model

### ISSUE THREAD

**Issue by gshanbhag525** [CropAi/Data-Modeling#76]
use image segmentation techniques to create a google collab notebook which consists of UNet model .

**Comment by Himabindugssn** [comment]
I want to work on this.

**Comment by abhishekgupta368** [comment]
Can I do this, please?

**Comment by gshanbhag525** [comment]
@Himabindugssn Any update on this isssue??

**Comment by Himabindugssn** [comment]
@gshanbhag525 I need some more time. Will get it done soon.

**Comment by gshanbhag525** [comment]
By tomorrow night you can submit a  PR @Himabindugssn . After that I will assign this to next particcipant @abhishekgupta368

**Comment by SubhradeepSS** [comment]
@gshanbhag525 Is the issue open to be taken?

**Comment by gshanbhag525** [comment]
@SubhradeepSS Yes go ahead.

**Comment by SubhradeepSS** [comment]
@gshanbhag525 We have to implement transfer learning for unet model,right?

**Comment by SubhradeepSS** [comment]
> 
> 
> @gshanbhag525 We have to implement transfer learning for unet model,right?

That is we have to use someone else's already built model for our own implementation?

**Comment by SubhradeepSS** [comment]
> 
> 
> @gshanbhag525 We have to implement transfer learning for unet model,right?

@gshanbhag525 If already trained models need to be implemented then we can use the python package segmentation-models which is available in pip-[https://pypi.org/project/segmentation-models/](https://pypi.org/project/segmentation-models/)

**Comment by gshanbhag525** [comment]
@SubhradeepSS yes u can use it.
