### ISSUE TITLE
Refine label images module

### ISSUE THREAD

**Issue by gshanbhag525** [CropAi/Data-Modeling#77]
Refine label images module and add metjod called predict and return the predictions

**Comment by AdityaSingh17** [comment]
I would like to take this up!

**Comment by abhishekgupta368** [comment]
I can do it

**Comment by nancysingh24** [comment]
> Refine label images module and add metjod called predict and return the predictions

When are the new issues gonna open?

**Comment by gshanbhag525** [comment]
> > Refine label images module and add metjod called predict and return the predictions
> 
> When are the new issues gonna open?

https://github.com/CropAi/Data-Modeling/issues/84
