### ISSUE TITLE
Add details about Data Modelling in Frontend/README

### ISSUE THREAD

**Issue by rajats98** [CropAi/Data-Modeling#79]
Update Frontend/README.md 
Refer this issue: https://github.com/CropAi/Frontend/issues/13

Under heading IMPORTANT LINKS, add details about data-modeling repo in brief (tech-stack, techniques, dataset etc.),  give it a heading (eg. Data-Modeling)
the link to repo should be there

**Comment by Adyasha8105** [comment]
sir, I want to work on this issue?

**Comment by rajats98** [comment]
Hey, Make a comment under CropAi/Frontend#13, then I will assign this to you also there itself.
