### ISSUE TITLE
Label Encoder file

### ISSUE THREAD

**Issue by vaibagga** [CropAi/Data-Modeling#84]
Write and save label encoder file in training and predict script

**Comment by nancysingh24** [comment]
I would like to work on this issue.

**Comment by voldemortuk** [comment]
I would like to work on the issue @gshanbhag525

**Comment by gshanbhag525** [comment]
@nancysingh24 Any update on this?

**Comment by nancysingh24** [comment]
> @nancysingh24 Any update on this?
 I just saw mail.i will start it by today.

**Comment by gshanbhag525** [comment]
@Valdermaut I am assigning this issue to u too. Start working on it. By tomorrow night submit the PR.

**Comment by voldemortuk** [comment]
@gshanbhag525 will do before Friday night saw this message a little but will do asap

**Comment by gshanbhag525** [comment]
@Valdermaut done?

**Comment by voldemortuk** [comment]
@gshanbhag525  I  guess the dataset does not require label encoding as it is not in css format. Please explain if what exactly needs to be done
