### ISSUE TITLE
Fine tune Keras model

### ISSUE THREAD

**Issue by gshanbhag525** [CropAi/Data-Modeling#85]
Fine tune Keras model to get correct predictions for all the 15 categories. The model is present in CropAI_keras jupyter notebook.

**Comment by SubhradeepSS** [comment]
@gshanbhag525 Would like to work on the issue

**Comment by gshanbhag525** [comment]
@SubhradeepSS  go ahead

**Comment by bhushanyadav07** [comment]
hey i'm interested to work on this issue I request you please assign me this issue thank you.

**Comment by gshanbhag525** [comment]
@bhushanyadav07 Are you still working on this issue? If not, I will close this issue.

**Comment by bhushanyadav07** [comment]
@gshanbhag525 I'm still working I request you sir please give me some time :)
